'use strict';
const CONTACT = { email: '', linkedin: 'https://www.linkedin.com/in/melusindoro' };
const scenarios = {
 recovery: {label:'Needs a closer look',title:'Two recovery figures. One question to resolve.',copy:'The investor deck uses 92% recovery. The technical report records 85% for its tested material. Before using either figure, confirm whether they describe the same ore and process.',evidence:[{label:'Investor deck assumption',value:'92%',unit:'recovery',source:'Investor deck · slide 14',doc:'deck'},{label:'Technical test result',value:'85%',unit:'recovery',source:'Technical report · page 86',doc:'report'}],note:'<strong>A possible mismatch, not a verdict.</strong> Different material or processing assumptions could explain the difference.',action:'Confirm the recovery basis',detail:'Suggested owner: technical lead',done:'Demo task assigned to the technical lead. The finding stays open until the evidence is reviewed.'},
 permit:{label:'Evidence gap',title:'The milestone is here. Its supporting document isn’t.',copy:'The investor deck says a water-use permit is expected before the next field programme. No permit decision appears in these three example documents. The project team needs to confirm its status.',evidence:[{label:'Planned milestone',value:'Water use',unit:'permit',source:'Investor deck · slide 18',doc:'permit-plan'},{label:'Evidence in this demo',value:'Not found',unit:'in 3 files',source:'Open the document index',doc:'index'}],note:'<strong>Missing from this pack does not mean missing in reality.</strong> Ask the project owner for the latest decision or application update.',action:'Request the permit evidence',detail:'Suggested owner: project director',done:'Demo evidence request assigned to the project director. The permit status remains unconfirmed.'},
 changes:{label:'Change to review',title:'The budget moved. The source explains where.',copy:'The current programme budget is US$2.4m, compared with US$2.1m in the previous column. The example workbook attributes the difference to additional testwork and an expanded drilling allowance.',evidence:[{label:'Previous review column',value:'$2.1m',unit:'USD',source:'Budget · Summary!B5',doc:'budget-old'},{label:'Current review column',value:'$2.4m',unit:'USD',source:'Budget · Summary!C5',doc:'budget-new'}],note:'<strong>A US$0.3m increase in this example.</strong> This comparison uses the same currency and programme scope labels; it does not approve the revised budget.',action:'Review the budget movement',detail:'Suggested owner: project director',done:'Demo budget review assigned to the project director. The previous review remains unchanged.'}
};
const documents={
 deck:{filename:'Kestrel-investor-deck.pdf',title:'Metallurgical assumptions',date:'Illustrative investor presentation · 18 September 2026',content:'<p>The development case assumes <mark>92% metallurgical recovery</mark>, subject to further testwork and confirmation of the process route.</p><p>Basis: management planning assumption. The source testwork and applicable ore domain are not identified on this slide.</p>',page:'Slide 14 · Synthetic data for demonstration only'},
 report:{filename:'Kestrel-technical-report.pdf',title:'Bench-scale recovery testwork',date:'Illustrative technical report · Effective 30 June 2026',content:'<p>The composite sample returned <mark>85% recovery under the tested bench-scale conditions</mark>.</p><p>Further work is required to establish whether this result represents all material domains and the proposed operating process.</p>',page:'PDF page 86 · Printed page 78 · Synthetic data'},
 'permit-plan':{filename:'Kestrel-investor-deck.pdf',title:'Field programme milestones',date:'Illustrative investor presentation · 18 September 2026',content:'<p>The next field programme is expected to begin after the <mark>water-use permit decision</mark> and mobilisation of the drilling contractor.</p><p>The decision date and reference number are not supplied in this example slide.</p>',page:'Slide 18 · Synthetic data'},
 index:{filename:'Example-document-index',title:'Documents available in this demo',date:'Three fictional source documents',content:'<p>1. Kestrel investor deck, 18 September 2026.</p><p>2. Kestrel technical report, effective 30 June 2026.</p><p>3. Kestrel programme budget, September 2026, containing previous and current review columns.</p><p><mark>No standalone permit decision is included.</mark> This is an index of the example pack, not the company’s complete records.</p>',page:'Document index · Synthetic data'},
 'budget-old':{filename:'Kestrel-programme-budget.xlsx',title:'Programme budget: previous review',date:'Illustrative workbook · Summary sheet',content:'<p>Cell B5, previous review total: <mark>US$2,100,000</mark>.</p><p>Column B represents the previous review snapshot. The currency is USD throughout this example.</p>',page:'Summary!B5 · Synthetic data'},
 'budget-new':{filename:'Kestrel-programme-budget.xlsx',title:'Programme budget: current review',date:'Illustrative workbook · Summary sheet',content:'<p>Cell C5, current review total: <mark>US$2,400,000</mark>.</p><p>Change note: an additional US$180,000 of metallurgical testwork and US$120,000 of drilling allowance.</p><p>Review state: proposed, pending approval.</p>',page:'Summary!C5 and Notes!A2:A3 · Synthetic data'}
};
let current='recovery';const reviewed=new Set();const $=id=>document.getElementById(id);
function renderScenario(key){current=key;const s=scenarios[key];document.querySelectorAll('[data-scenario]').forEach(b=>{b.classList.toggle('active',b.dataset.scenario===key);b.setAttribute('aria-pressed',String(b.dataset.scenario===key));});$('finding-label').textContent=s.label;$('finding-position').textContent=`Finding ${Object.keys(scenarios).indexOf(key)+1} of 3`;$('answer-title').textContent=s.title;$('answer-copy').textContent=s.copy;$('answer-note').innerHTML=s.note;$('action-title').textContent=s.action;$('action-detail').textContent=s.detail;$('evidence-grid').innerHTML=s.evidence.map(e=>`<button class="evidence" data-doc="${e.doc}"><span class="evidence-label">${e.label}</span><span class="evidence-value">${e.value}<span class="evidence-unit">${e.unit}</span></span><span class="evidence-source">${e.source}<span aria-hidden="true">↗</span></span></button>`).join('');$('review-button').disabled=reviewed.has(key);$('review-button').innerHTML=reviewed.has(key)?'Review assigned <span aria-hidden="true">✓</span>':'Assign a review <span aria-hidden="true">+</span>';$('review-confirmation').textContent=reviewed.has(key)?s.done:'';}
document.querySelectorAll('[data-scenario]').forEach(b=>b.addEventListener('click',()=>renderScenario(b.dataset.scenario)));
$('evidence-grid').addEventListener('click',e=>{const b=e.target.closest('[data-doc]');if(!b)return;const d=documents[b.dataset.doc];$('source-filename').textContent=d.filename;$('source-heading').textContent=d.title;$('source-date').textContent=d.date;$('source-content').innerHTML=d.content;$('source-page').textContent=d.page;$('source-dialog').showModal();});
$('review-button').addEventListener('click',()=>{reviewed.add(current);renderScenario(current);});
$('reset-demo').addEventListener('click',()=>{reviewed.clear();renderScenario('recovery');showToast('The fictional project has been reset.');});
$('layers-button').addEventListener('click',()=>{const isOpen=$('hero-art').classList.toggle('is-open');$('layers-button').setAttribute('aria-pressed',String(isOpen));$('layers-button').innerHTML=isOpen?'<span aria-hidden="true">≋</span> Bring it together':'<span aria-hidden="true">≋</span> Explore the layers';});
const motion=window.matchMedia('(prefers-reduced-motion: reduce)');$('hero-art').addEventListener('pointermove',e=>{if(motion.matches||e.pointerType==='touch')return;const r=e.currentTarget.getBoundingClientRect();$('formation').style.setProperty('--ry',`${((e.clientX-r.left)/r.width-.5)*9}deg`);$('formation').style.setProperty('--rx',`${((e.clientY-r.top)/r.height-.5)*-7}deg`);});$('hero-art').addEventListener('pointerleave',()=>{$('formation').style.setProperty('--rx','0deg');$('formation').style.setProperty('--ry','0deg');});
document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).close()));document.querySelectorAll('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}));
let enquiryType='pilot';document.querySelectorAll('[data-enquire]').forEach(b=>b.addEventListener('click',()=>{enquiryType=b.dataset.enquire;const hiring=enquiryType!=='pilot';$('enquiry-heading').textContent=hiring?'Let’s build Orethread.':'What are you working on?';$('enquiry-intro').textContent=hiring?'Tell us about something you’ve built and the work you want to own.':'A little context will help us make the first conversation useful.';$('message-label').firstChild.textContent=hiring?'What have you built? Include a project or portfolio link.':'What would you like to work through?';$('company-label').firstChild.textContent=hiring?'Your current work or project':'Company or project';$('enquiry-form').reset();$('enquiry-form').hidden=false;$('enquiry-result').hidden=true;$('copy-status').textContent='Your message has not been sent.';$('enquiry-dialog').showModal();}));
$('enquiry-form').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);const role=enquiryType==='pilot'?'A project pilot':enquiryType==='product'?'Product and engineering co-founder':'AI and data co-founder';const msg=`Hi Melusi,\n\nI’d like to discuss ${role.toLowerCase()} with Orethread.\n\nName: ${String(f.get('name')).trim()}\nEmail: ${String(f.get('email')).trim()}\nCompany / project: ${String(f.get('company')).trim()}\n\n${String(f.get('message')).trim()}\n\nThanks,\n${String(f.get('name')).trim()}`;$('prepared-message').value=msg;$('enquiry-form').hidden=true;$('enquiry-result').hidden=false;if(CONTACT.email){$('enquiry-result').querySelector('p').textContent='Your introduction is ready. Open your email app to review and send it.';$('send-introduction').href=`mailto:${CONTACT.email}?subject=${encodeURIComponent('Orethread: '+role)}&body=${encodeURIComponent(msg)}`;$('send-introduction').textContent='Open email app ↗';}else{$('send-introduction').href=CONTACT.linkedin;$('send-introduction').textContent='Open LinkedIn ↗';}});
$('copy-introduction').addEventListener('click',async()=>{try{await navigator.clipboard.writeText($('prepared-message').value);$('copy-status').textContent='Copied. Open LinkedIn and paste it into your message to Melusi.';}catch{$('prepared-message').focus();$('prepared-message').select();$('copy-status').textContent='Select and copy the introduction above, then send it to Melusi.';}});
let toastTimer;function showToast(t){$('toast').textContent=t;$('toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('visible'),3500);}
$('download-example').addEventListener('click',()=>{const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;');const text=`<!doctype html><html lang="en"><meta charset="utf-8"><title>Orethread fictional diligence example</title><style>body{font:16px system-ui;max-width:800px;margin:50px auto;padding:20px;line-height:1.8}article{margin:40px 0}h1,h2{line-height:1.2}small{display:block}</style><h1>Kestrel Copper: illustrative review</h1><p>Fictional data. This is a product demonstration, not an assessment of a real mining project.</p>${Object.values(scenarios).map(s=>`<article><h2>${esc(s.title)}</h2><p>${esc(s.copy)}</p>${s.evidence.map(e=>`<p><strong>${esc(e.value)} ${esc(e.unit)}</strong><small>${esc(e.source)}</small></p>`).join('')}<p>${s.note}</p><p>Next action: ${esc(s.action)}. ${esc(s.detail)}.</p></article>`).join('')}<h2>Source excerpts</h2>${Object.values(documents).map(d=>`<article><h3>${esc(d.title)}</h3><p>${esc(d.filename)}: ${esc(d.page)}</p>${d.content}</article>`).join('')}<p>Created from the Orethread interactive demo.</p></html>`;const a=document.createElement('a');const u=URL.createObjectURL(new Blob([text],{type:'text/html'}));a.href=u;a.download='orethread-fictional-diligence-example.html';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);showToast('Your fictional example is ready to download.');});
renderScenario('recovery');
